SET SCHEMA DM_PAL;

DROP TABLE #PAL_PARAMETER_TBL;
CREATE LOCAL TEMPORARY COLUMN TABLE #PAL_PARAMETER_TBL (
	"PARAM_NAME " VARCHAR(100),
	"INT_VALUE" INTEGER, 
	"DOUBLE_VALUE" DOUBLE, 
	"STRING_VALUE" VARCHAR (100)
);

INSERT INTO #PAL_PARAMETER_TBL VALUES ('ADAPTIVE_METHOD',0, NULL, NULL);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('MEASURE_NAME', NULL, NULL, 'MSE');
INSERT INTO #PAL_PARAMETER_TBL VALUES ('ALPHA', NULL,0.1, NULL);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('DELTA', NULL,0.2, NULL);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('FORECAST_NUM',12, NULL,NULL);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('EXPOST_FLAG',1, NULL,NULL);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('PREDICTION_CONFIDENCE_1', NULL, 0.8, NULL);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('PREDICTION_CONFIDENCE_2', NULL, 0.95, NULL);

DROP TABLE PAL_SINGLESMOOTH_DATA_TBL;
CREATE COLUMN TABLE PAL_SINGLESMOOTH_DATA_TBL ("ID" INT, "RAWDATA" DOUBLE);

INSERT INTO PAL_SINGLESMOOTH_DATA_TBL VALUES (1,200.0);
INSERT INTO PAL_SINGLESMOOTH_DATA_TBL VALUES (2,135.0);
INSERT INTO PAL_SINGLESMOOTH_DATA_TBL VALUES (3,195.0);
INSERT INTO PAL_SINGLESMOOTH_DATA_TBL VALUES (4,197.5);
INSERT INTO PAL_SINGLESMOOTH_DATA_TBL VALUES (5,310.0);
INSERT INTO PAL_SINGLESMOOTH_DATA_TBL VALUES (6,175.0);
INSERT INTO PAL_SINGLESMOOTH_DATA_TBL VALUES (7,155.0);
INSERT INTO PAL_SINGLESMOOTH_DATA_TBL VALUES (8,130.0);
INSERT INTO PAL_SINGLESMOOTH_DATA_TBL VALUES (9,220.0);
INSERT INTO PAL_SINGLESMOOTH_DATA_TBL VALUES (10,277.5);
INSERT INTO PAL_SINGLESMOOTH_DATA_TBL VALUES (11,235.0);

CALL _SYS_AFL.PAL_SINGLE_EXPSMOOTH(PAL_SINGLESMOOTH_DATA_TBL, #PAL_PARAMETER_TBL, ?,?);
