SET SCHEMA DM_PAL ;

DROP TABLE #PAL_PARAMETER_TBL;
CREATE LOCAL TEMPORARY COLUMN TABLE #PAL_PARAMETER_TBL (
	"PARAM_NAME " VARCHAR(100),
	"INT_VALUE" INTEGER, 
	"DOUBLE_VALUE" DOUBLE, 
	"STRING_VALUE" VARCHAR (100)
);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('MIN_SUPPORT', null, 0.1, null);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('MIN_CONFIDENCE', null, 0.3, null);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('MIN_LIFT', null, 1.1, null);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('MAX_CONSEQUENT', 1, null, null);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('PMML_EXPORT', 1, null, null);

DROP TABLE PAL_APRIORI_TRANS_TBL;
CREATE COLUMN TABLE PAL_APRIORI_TRANS_TBL (
	"CUSTOMER" INTEGER,
	"ITEM" VARCHAR(20)
);
INSERT INTO PAL_APRIORI_TRANS_TBL VALUES (2, 'item2');
INSERT INTO PAL_APRIORI_TRANS_TBL VALUES (2, 'item3');
INSERT INTO PAL_APRIORI_TRANS_TBL VALUES (3, 'item1');
INSERT INTO PAL_APRIORI_TRANS_TBL VALUES (3, 'item2');
INSERT INTO PAL_APRIORI_TRANS_TBL VALUES (3, 'item4');
INSERT INTO PAL_APRIORI_TRANS_TBL VALUES (4, 'item1');
INSERT INTO PAL_APRIORI_TRANS_TBL VALUES (4, 'item3');
INSERT INTO PAL_APRIORI_TRANS_TBL VALUES (5, 'item2');
INSERT INTO PAL_APRIORI_TRANS_TBL VALUES (5, 'item3');
INSERT INTO PAL_APRIORI_TRANS_TBL VALUES (6, 'item1');
INSERT INTO PAL_APRIORI_TRANS_TBL VALUES (6, 'item3');
INSERT INTO PAL_APRIORI_TRANS_TBL VALUES (0, 'item1');
INSERT INTO PAL_APRIORI_TRANS_TBL VALUES (0, 'item2');
INSERT INTO PAL_APRIORI_TRANS_TBL VALUES (0, 'item5');
INSERT INTO PAL_APRIORI_TRANS_TBL VALUES (1, 'item2');
INSERT INTO PAL_APRIORI_TRANS_TBL VALUES (1, 'item4'); 
INSERT INTO PAL_APRIORI_TRANS_TBL VALUES (7, 'item1');
INSERT INTO PAL_APRIORI_TRANS_TBL VALUES (7, 'item2');
INSERT INTO PAL_APRIORI_TRANS_TBL VALUES (7, 'item3');
INSERT INTO PAL_APRIORI_TRANS_TBL VALUES (7, 'item5');
INSERT INTO PAL_APRIORI_TRANS_TBL VALUES (8, 'item1');
INSERT INTO PAL_APRIORI_TRANS_TBL VALUES (8, 'item2');
INSERT INTO PAL_APRIORI_TRANS_TBL VALUES (8, 'item3');

CALL _SYS_AFL.PAL_APRIORI(PAL_APRIORI_TRANS_TBL, #PAL_PARAMETER_TBL, ?, ?);