SET SCHEMA DM_PAL;

DROP TABLE PAL_DISTRIBUTION_FIT_DATA_TBL;
CREATE COLUMN TABLE PAL_DISTRIBUTION_FIT_DATA_TBL ("DATA" DOUBLE);
INSERT INTO PAL_DISTRIBUTION_FIT_DATA_TBL VALUES (71);
INSERT INTO PAL_DISTRIBUTION_FIT_DATA_TBL VALUES (83);
INSERT INTO PAL_DISTRIBUTION_FIT_DATA_TBL VALUES (92);
INSERT INTO PAL_DISTRIBUTION_FIT_DATA_TBL VALUES (104);
INSERT INTO PAL_DISTRIBUTION_FIT_DATA_TBL VALUES (120);
INSERT INTO PAL_DISTRIBUTION_FIT_DATA_TBL VALUES (134);
INSERT INTO PAL_DISTRIBUTION_FIT_DATA_TBL VALUES (138);
INSERT INTO PAL_DISTRIBUTION_FIT_DATA_TBL VALUES (146);
INSERT INTO PAL_DISTRIBUTION_FIT_DATA_TBL VALUES (181);
INSERT INTO PAL_DISTRIBUTION_FIT_DATA_TBL VALUES (191);
INSERT INTO PAL_DISTRIBUTION_FIT_DATA_TBL VALUES (206);
INSERT INTO PAL_DISTRIBUTION_FIT_DATA_TBL VALUES (226);
INSERT INTO PAL_DISTRIBUTION_FIT_DATA_TBL VALUES (276);
INSERT INTO PAL_DISTRIBUTION_FIT_DATA_TBL VALUES (283);
INSERT INTO PAL_DISTRIBUTION_FIT_DATA_TBL VALUES (291);
INSERT INTO PAL_DISTRIBUTION_FIT_DATA_TBL VALUES (332);
INSERT INTO PAL_DISTRIBUTION_FIT_DATA_TBL VALUES (351);
INSERT INTO PAL_DISTRIBUTION_FIT_DATA_TBL VALUES (401);
INSERT INTO PAL_DISTRIBUTION_FIT_DATA_TBL VALUES (466);

DROP TABLE #PAL_PARAMETER_TBL;
CREATE LOCAL TEMPORARY COLUMN TABLE #PAL_PARAMETER_TBL ("PARAM_NAME" VARCHAR(256), "INT_VALUE" INTEGER, "DOUBLE_VALUE" DOUBLE, "STRING_VALUE" VARCHAR(1000));
INSERT INTO #PAL_PARAMETER_TBL VALUES ('DISTRIBUTIONNAME', NULL, NULL, 'WEIBULL');
INSERT INTO #PAL_PARAMETER_TBL VALUES ('OPTIMAL_METHOD', 0, NULL, NULL);

CALL _SYS_AFL.PAL_DISTRIBUTION_FIT (PAL_DISTRIBUTION_FIT_DATA_TBL, #PAL_PARAMETER_TBL, ?, ?);