SET SCHEMA DM_PAL;

DROP TABLE PAL_MISSING_VALUES_DATA_TBL;
CREATE COLUMN TABLE PAL_MISSING_VALUES_DATA_TBL ("V0" INTEGER, "V1" INTEGER, "V2" VARCHAR(5), "V3" DOUBLE, "V4" DOUBLE, "V5" DOUBLE);

INSERT INTO PAL_MISSING_VALUES_DATA_TBL VALUES (10,   0,    'D',  NULL, 1.4,  23.6);
INSERT INTO PAL_MISSING_VALUES_DATA_TBL VALUES (20,   1,    'A',  0.4,  1.3,  21.8);
INSERT INTO PAL_MISSING_VALUES_DATA_TBL VALUES (50,   1,    'C',  NULL, 1.6,  21.9);
INSERT INTO PAL_MISSING_VALUES_DATA_TBL VALUES (30,   NULL, 'B',  0.8,  1.7,  22.6);
INSERT INTO PAL_MISSING_VALUES_DATA_TBL VALUES (10,   0,    'A',  0.2,  NULL, NULL);
INSERT INTO PAL_MISSING_VALUES_DATA_TBL VALUES (10,   0,    NULL, 0.5,  1.8,  19.7);
INSERT INTO PAL_MISSING_VALUES_DATA_TBL VALUES (NULL, 0,    'C',  0.5,  NULL, 17.8);
INSERT INTO PAL_MISSING_VALUES_DATA_TBL VALUES (10,   1,    'A',  0.6,  1.6,  24.9);
INSERT INTO PAL_MISSING_VALUES_DATA_TBL VALUES (20,   NULL, 'D',  0.9,  1.7,  22.2);
INSERT INTO PAL_MISSING_VALUES_DATA_TBL VALUES (30,   1,    'D',  0.4,  1.3,  NULL);
INSERT INTO PAL_MISSING_VALUES_DATA_TBL VALUES (50,   0,    NULL, 0.3,  1.2,  16.4);
INSERT INTO PAL_MISSING_VALUES_DATA_TBL VALUES (NULL, 1,    'B',  0.7,  1.2,  19.3);
INSERT INTO PAL_MISSING_VALUES_DATA_TBL VALUES (30,   1,    'A',  0.2,  1.1,  21.7);
INSERT INTO PAL_MISSING_VALUES_DATA_TBL VALUES (30,   0,    'D',  NULL, NULL, NULL);
INSERT INTO PAL_MISSING_VALUES_DATA_TBL VALUES (NULL, 1,    'C',  0.5,  1.8,  18.6);
INSERT INTO PAL_MISSING_VALUES_DATA_TBL VALUES (20,   0,    'A',  0.6,  1.4,  17.9);

DROP TABLE #PAL_PARAMETER_TBL;
CREATE LOCAL TEMPORARY COLUMN TABLE #PAL_PARAMETER_TBL ("PARAM_NAME" VARCHAR (256), "INT_VALUE" INTEGER, "DOUBLE_VALUE" DOUBLE, "STRING_VALUE" VARCHAR (1000));
INSERT INTO #PAL_PARAMETER_TBL VALUES ('IMPUTATION_TYPE', 1, NULL, NULL); -- use overall imputation type MODE_MEAN
INSERT INTO #PAL_PARAMETER_TBL VALUES ('CATEGORICAL_VARIABLE', NULL, NULL, 'V1'); -- indicate that 'V1' is a categorical variable
INSERT INTO #PAL_PARAMETER_TBL VALUES ('V1_IMPUTATION_TYPE', 101, NULL, '0'); -- set imputation type of column 'V1' to be 101 (SPECIFIED_CATEGORICAL_VALUE), and the specified categorical value to be '0'

DROP TABLE PAL_MISSING_VALUES_STATISTICS_TBL;
CREATE COLUMN TABLE PAL_MISSING_VALUES_STATISTICS_TBL ("STAT_NAME" NVARCHAR(256), "STAT_VALUE" NVARCHAR(5000));

CALL "_SYS_AFL"."PAL_MISSING_VALUE_HANDLING"(PAL_MISSING_VALUES_DATA_TBL, #PAL_PARAMETER_TBL, ?, ?);
