SET SCHEMA DM_PAL;

DROP TABLE PAL_MASSIVE_SINGLESMOOTH_DATA_TBL;
CREATE COLUMN TABLE PAL_MASSIVE_SINGLESMOOTH_DATA_TBL (
    GROUP_ID NVARCHAR(40),
    TIMESTAMP INTEGER,
    VALUE DOUBLE
);

DROP TABLE PAL_MASSIVE_SINGLESMOOTH_PARAM_TBL;
CREATE COLUMN TABLE PAL_MASSIVE_SINGLESMOOTH_PARAM_TBL (
    GROUP_ID NVARCHAR(40),
    NAME NVARCHAR(100),
    INTARGS INTEGER,
    DOUBLEARGS DOUBLE,
    STRINGARGS NVARCHAR(100)
);

DROP TABLE PAL_MASSIVE_SINGLESMOOTH_FORECAST_TBL;
CREATE COLUMN TABLE PAL_MASSIVE_SINGLESMOOTH_FORECAST_TBL (
    GROUP_ID NVARCHAR(40),
    TIMESTAMP INTEGER,
    VALUE DOUBLE
);

DROP TABLE PAL_MASSIVE_SINGLESMOOTH_STAT_TBL;
CREATE COLUMN TABLE PAL_MASSIVE_SINGLESMOOTH_STAT_TBL (
    GROUP_ID NVARCHAR(40),
    STAT_NAME NVARCHAR(50),
    STAT_VALUE DOUBLE
);

DROP TABLE PAL_MASSIVE_SINGLESMOOTH_ERROR_TBL;
CREATE COLUMN TABLE PAL_MASSIVE_SINGLESMOOTH_ERROR_TBL (
    GROUP_ID NVARCHAR(40),
    ERROR_TIMESTAMP NVARCHAR(100),
    ERRORCODE INTEGER,
    ERROR_MESSAGE NVARCHAR(200)
);

DROP TABLE PAL_SES_PDATA_TBL;
CREATE COLUMN TABLE PAL_SES_PDATA_TBL ("POSITION" INT, "SCHEMA_NAME" NVARCHAR(256), "TYPE_NAME" NVARCHAR(256), "PARAMETER_TYPE" VARCHAR(7));
INSERT INTO PAL_SES_PDATA_TBL VALUES(1,'DM_PAL', 'PAL_MASSIVE_SINGLESMOOTH_DATA_TBL','IN');
INSERT INTO PAL_SES_PDATA_TBL VALUES(2,'DM_PAL', 'PAL_MASSIVE_SINGLESMOOTH_PARAM_TBL','IN'); 
INSERT INTO PAL_SES_PDATA_TBL VALUES(3,'DM_PAL', 'PAL_MASSIVE_SINGLESMOOTH_FORECAST_TBL','OUT');
INSERT INTO PAL_SES_PDATA_TBL VALUES(4,'DM_PAL', 'PAL_MASSIVE_SINGLESMOOTH_STAT_TBL','OUT');
INSERT INTO PAL_SES_PDATA_TBL VALUES(5,'DM_PAL', 'PAL_MASSIVE_SINGLESMOOTH_ERROR_TBL','OUT');

CALL SYS.AFLLANG_WRAPPER_PROCEDURE_DROP('DM_PAL', 'PAL_SES_AFL_WRAPPER_MASS'); 
CALL SYS.AFLLANG_WRAPPER_PROCEDURE_CREATE('AFLPAL', 'MASSIVE_SINGLESMOOTH', 'DM_PAL', 'PAL_SES_AFL_WRAPPER_MASS', PAL_SES_PDATA_TBL);

TRUNCATE TABLE PAL_MASSIVE_SINGLESMOOTH_DATA_TBL;
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_DATA_TBL VALUES ('A', 1,200.0);
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_DATA_TBL VALUES ('A', 2,135.0);
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_DATA_TBL VALUES ('A', 3,195.0);
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_DATA_TBL VALUES ('A', 4,197.5);
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_DATA_TBL VALUES ('A', 5,310.0);
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_DATA_TBL VALUES ('A', 6,175.0);
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_DATA_TBL VALUES ('A', 7,155.0);
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_DATA_TBL VALUES ('A', 8,130.0);
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_DATA_TBL VALUES ('A', 9,220.0);
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_DATA_TBL VALUES ('A', 10,277.5);
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_DATA_TBL VALUES ('A', 11,235.0);
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_DATA_TBL VALUES ('B', 1,200.0);
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_DATA_TBL VALUES ('B', 2,135.0);
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_DATA_TBL VALUES ('B', 3,195.0);
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_DATA_TBL VALUES ('B', 4,197.5);
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_DATA_TBL VALUES ('B', 5,310.0);
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_DATA_TBL VALUES ('B', 6,175.0);
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_DATA_TBL VALUES ('B', 7,155.0);
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_DATA_TBL VALUES ('B', 8,130.0);
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_DATA_TBL VALUES ('B', 9,220.0);
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_DATA_TBL VALUES ('B', 10,277.5);
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_DATA_TBL VALUES ('B', 11,235.0);

TRUNCATE TABLE PAL_MASSIVE_SINGLESMOOTH_PARAM_TBL;
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_PARAM_TBL VALUES ('PAL_MASSIVE_PROCESSING_SPECIAL_GROUP_ID', 'ADAPTIVE_METHOD',0, NULL, NULL);
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_PARAM_TBL VALUES ('PAL_MASSIVE_PROCESSING_SPECIAL_GROUP_ID', 'MEASURE_NAME', NULL, NULL, 'MSE');
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_PARAM_TBL VALUES ('PAL_MASSIVE_PROCESSING_SPECIAL_GROUP_ID', 'ALPHA', NULL,0.1, NULL);
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_PARAM_TBL VALUES ('PAL_MASSIVE_PROCESSING_SPECIAL_GROUP_ID', 'DELTA', NULL,0.2, NULL);
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_PARAM_TBL VALUES ('PAL_MASSIVE_PROCESSING_SPECIAL_GROUP_ID', 'FORECAST_NUM',12, NULL,NULL);
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_PARAM_TBL VALUES ('PAL_MASSIVE_PROCESSING_SPECIAL_GROUP_ID', 'EXPOST_FLAG',1, NULL,NULL);
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_PARAM_TBL VALUES ('PAL_MASSIVE_PROCESSING_SPECIAL_GROUP_ID', 'PREDICTION_CONFIDENCE_1', NULL, 0.8, NULL);
INSERT INTO PAL_MASSIVE_SINGLESMOOTH_PARAM_TBL VALUES ('PAL_MASSIVE_PROCESSING_SPECIAL_GROUP_ID', 'PREDICTION_CONFIDENCE_2', NULL, 0.95, NULL);

CALL DM_PAL.PAL_SES_AFL_WRAPPER_MASS(PAL_MASSIVE_SINGLESMOOTH_DATA_TBL, PAL_MASSIVE_SINGLESMOOTH_PARAM_TBL, ?, ?, ?);