SET SCHEMA DM_PAL;

DROP TABLE PAL_SVM_DATA_TBL;
CREATE COLUMN TABLE PAL_SVM_DATA_TBL (
    "ID" INTEGER,
    "ATTRIBUTE1" DOUBLE,
    "ATTRIBUTE2" DOUBLE,
    "ATTRIBUTE3" DOUBLE,
    "ATTRIBUTE4" VARCHAR(10),
    "LABEL" INTEGER
);
INSERT INTO PAL_SVM_DATA_TBL VALUES (0, 1, 10, 100, 'A', 1);
INSERT INTO PAL_SVM_DATA_TBL VALUES (1, 1.1, 10.1, 100,'A', 1);
INSERT INTO PAL_SVM_DATA_TBL VALUES (2, 1.2, 10.2, 100, 'A', 1);
INSERT INTO PAL_SVM_DATA_TBL VALUES (3, 1.3, 10.4, 100, 'A', 1);
INSERT INTO PAL_SVM_DATA_TBL VALUES (4, 1.2, 10.3, 100, 'AB', 1);
INSERT INTO PAL_SVM_DATA_TBL VALUES (5, 4, 40, 400, 'AB', 2);
INSERT INTO PAL_SVM_DATA_TBL VALUES (6, 4.1, 40.1, 400, 'AB', 2);
INSERT INTO PAL_SVM_DATA_TBL VALUES (7, 4.2, 40.2, 400, 'AB', 2);
INSERT INTO PAL_SVM_DATA_TBL VALUES (8, 4.3, 40.4, 400, 'AB', 2);
INSERT INTO PAL_SVM_DATA_TBL VALUES (9, 4.2, 40.3, 400, 'AB', 2);
INSERT INTO PAL_SVM_DATA_TBL VALUES (10, 9, 90, 900, 'B', 3);
INSERT INTO PAL_SVM_DATA_TBL VALUES (11, 9.1, 90.1, 900, 'A', 3);
INSERT INTO PAL_SVM_DATA_TBL VALUES (12, 9.2, 90.2, 900, 'B', 3);
INSERT INTO PAL_SVM_DATA_TBL VALUES (13, 9.3, 90.4, 900, 'A', 3);
INSERT INTO PAL_SVM_DATA_TBL VALUES (14, 9.2, 90.3, 900, 'A', 3);

DROP TABLE #PAL_PARAMETER_TBL;
CREATE LOCAL TEMPORARY COLUMN TABLE #PAL_PARAMETER_TBL (
    "PARAM_NAME" NVARCHAR(256),
    "INT_VALUE" INTEGER, 
    "DOUBLE_VALUE" DOUBLE, 
    "STRING_VALUE" NVARCHAR (1000)
);

-- specify SVM parameter
INSERT INTO #PAL_PARAMETER_TBL VALUES ('HAS_ID', 1, NULL, NULL);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('THREAD_RATIO', NULL, 1, NULL);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('TYPE', 1, NULL, NULL); -- fixed
INSERT INTO #PAL_PARAMETER_TBL VALUES ('KERNEL_TYPE', 3, NULL, NULL); -- fixed

-- specify parameter selection settings
INSERT INTO #PAL_PARAMETER_TBL VALUES ('RESAMPLING_METHOD', NULL, NULL, 'bootstrap');
INSERT INTO #PAL_PARAMETER_TBL VALUES ('EVALUATION_METRIC', NULL, NULL, 'ACCURACY');
INSERT INTO #PAL_PARAMETER_TBL VALUES ('REPEAT_TIMES', 2, NULL, NULL);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('PARAM_SEARCH_STRATEGY', NULL, NULL, 'grid');
INSERT INTO #PAL_PARAMETER_TBL VALUES ('SEED', 1, NULL, NULL);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('PROGRESS_INDICATOR_ID', NULL, NULL, 'TEST');

-- specify SVM parameter candidates
INSERT INTO #PAL_PARAMETER_TBL VALUES ('SVM_C_VALUES', NULL, NULL, '{1, 10, 21, 100}');
INSERT INTO #PAL_PARAMETER_TBL VALUES ('COEF_LIN_RANGE', NULL, NULL, '[0.005, 0.001, 0.007]'); -- equivalent to {0.005, 0.006, 0.007} 
INSERT INTO #PAL_PARAMETER_TBL VALUES ('COEF_CONST_RANGE', NULL, NULL, '[0.003, 0.002, 0.006]'); -- equivalent to {0.003, 0.005}

-- call procedure
CALL _SYS_AFL.PAL_SVM(PAL_SVM_DATA_TBL, "#PAL_PARAMETER_TBL", ?, ?, ?);