SET SCHEMA DM_PAL;

DROP TABLE PAL_MODEL_COMP_DATA_TBL;
CREATE COLUMN TABLE PAL_MODEL_COMP_DATA_TBL 
    ("ID" INTEGER, "Y" DOUBLE, "X1" DOUBLE);

INSERT INTO PAL_MODEL_COMP_DATA_TBL VALUES (0, 6.879, 0.02);
INSERT INTO PAL_MODEL_COMP_DATA_TBL VALUES (1, 3.449, 0.50);
INSERT INTO PAL_MODEL_COMP_DATA_TBL VALUES (2,  6.635, 0.54);
INSERT INTO PAL_MODEL_COMP_DATA_TBL VALUES (3, 11.844, 1.04);
INSERT INTO PAL_MODEL_COMP_DATA_TBL VALUES (4,  2.786, 1.50);
INSERT INTO PAL_MODEL_COMP_DATA_TBL VALUES (5,  2.389, 0.04);
INSERT INTO PAL_MODEL_COMP_DATA_TBL VALUES (6, 0.011, 2.00);
INSERT INTO PAL_MODEL_COMP_DATA_TBL VALUES (7,  8.839, 2.04);
INSERT INTO PAL_MODEL_COMP_DATA_TBL VALUES (8,  4.689, 1.54);
INSERT INTO PAL_MODEL_COMP_DATA_TBL VALUES (9, 5.507, 1.00);

DROP TABLE PAL_MC_CONFIG_TBL;
CREATE COLUMN TABLE PAL_MC_CONFIG_TBL
("MODEL_ID" INT,
"MODEL_NAME" VARCHAR(20),
"MODEL_CONFIG" VARCHAR(100)
);
INSERT INTO PAL_MC_CONFIG_TBL VALUES (1, 'MLR', '{"ALG": 4, "ENET_ALPHA":0.5}'); //Cyclical coordinate descent method to solve elastic net regularized multiple linear regression
INSERT INTO PAL_MC_CONFIG_TBL VALUES (2, 'MLR', '{"ALG": 2}'); //SVD (solving the least square problem)
INSERT INTO PAL_MC_CONFIG_TBL VALUES (3, 'SVM', '{"KERNEL_TYPE": 0}');

DROP TABLE #PAL_PARAMETER_TBL;
CREATE LOCAL TEMPORARY COLUMN TABLE #PAL_PARAMETER_TBL (
    "PARAM_NAME" NVARCHAR(256),
    "INT_VALUE" INTEGER, 
    "DOUBLE_VALUE" DOUBLE, 
    "STRING_VALUE" NVARCHAR (1000)
);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('RANDOM_SEED',10,NULL,NULL);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('HAS_ID',1,NULL,NULL);
INSERT INTO #PAL_PARAMETER_TBL VALUES ('DEPENDENT_VARIABLE',NULL,NULL,'Y');
INSERT INTO #PAL_PARAMETER_TBL VALUES ('TRAINING_PERCENT',NULL,0.6,NULL);

CALL _SYS_AFL.PAL_MODEL_COMPARISON_REGRESSION(PAL_MODEL_COMP_DATA_TBL, PAL_MC_CONFIG_TBL, #PAL_PARAMETER_TBL, ?, ?, ?, ?, ?, ?);
